### ISSUE TITLE
Change fullscreen CSS from `top`/`bottom`/`left`/`right` to `inset`

### ISSUE THREAD

**Issue by mfreed7** [whatwg/fullscreen#201]
The fullscreen spec says this:

```css
*|*:not(:root):fullscreen {
  top:0 !important; right:0 !important; bottom:0 !important; left:0 !important;
}
::backdrop {
  top:0; right:0; bottom:0; left:0;
}
```

For brevity and (small) performance improvement, would it be better to do this?

```css
*|*:not(:root):fullscreen {
  inset:0 !important;
}
::backdrop {
  inset:0;
}
```

On at least Chromium, `inset:0` can be faster than individual `top`/`left`/`bottom`/`right` properties. And the notation is easier to understand. This also seems like a web-compatible change to make.

@dbaron @bfgeek
